In [60]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [61]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [62]:
c = (zp * ks).mean() - zp.mean() * ks.mean()
c

9157.839999999997

In [63]:
np.cov(zp, ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [64]:
np.cov(zp, ks)[0, 1]

10175.377777777776

In [65]:
np.cov(zp, ks, ddof = 0)[0, 1]

9157.84

In [66]:
ks.std(ddof = 1)

183.99544076477068

In [67]:
zp.std(ddof = 1)

62.31318747531162

In [68]:
10175.3777 / (ks.std(ddof = 1) * zp.std(ddof = 1))

0.8874900852901869

In [69]:
9157.84 /(zp.std() * ks.std()) 

0.8874900920739162