In [ ]:
## Провести дисперсионный анализ для определения того, 
есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. 
Даны значения роста в трех группах случайно выбранных спортсменов: Футболисты: 
173, 175, 180, 178, 177, 185, 183, 182. 
Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. 
Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

In [1]:
import numpy as np

In [4]:
from scipy import stats

In [5]:
stats.f_oneway?

In [6]:
y1 = np.array([173, 175, 180, 178, 177, 185, 183, 182])
y1

array([173, 175, 180, 178, 177, 185, 183, 182])

In [7]:
y2 = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
y2

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [8]:
y3 = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
y3

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [10]:
stats.f_oneway(y1, y2, y3)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

In [ ]:
## Дополнительно найдем F (крит.) в таблице критических точек распределения Фишера-Снедекора 
для альфа = 0.05 и двух степеней свободы: F (крит.) = 3.3852. F (H) > F (крит.), поэтому отвергнута гипотеза Н0, 
различие роста в трех группах статистически значимо.