In [1]:
import numpy as np

In [2]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [3]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [4]:
n = len(X)
n

10

In [6]:
b = (np.mean(X*y)-np.mean(X)*np.mean(y))/(np.mean(X**2)-np.mean(X)**2)
b

2.620538882402765

In [8]:
a = np.mean(y)-b*np.mean(X)
a

444.1773573243596

In [9]:
## Без интерсепта

In [10]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [11]:
X = X.reshape((10, 1))
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [12]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [13]:
y = y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [15]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)), X.T @ y)
B

array([[5.88982042]])

In [16]:
## Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept)

In [17]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [18]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [19]:
def mse_(B1, y=y, X=X, n=10):
    return np.sum((B1*X-y)**2)/n

In [20]:
B1 = 0.5

In [21]:
alpha = 1e-6
alpha

1e-06

In [24]:
for i in range(100000):
    B1 -= alpha*(2/n)*np.sum((B1*X-y)*X)
    if i%20000 == 0:
        print('Iteration: {i}, B1={B1}, mse={mse}'.format(i=i, B1=B1, mse=mse_(B1)))

Iteration: 0, B1=0.7929217624382401, mse=414410.55220897525
Iteration: 20000, B1=5.889820420132673, mse=56516.85841571943
Iteration: 40000, B1=5.889820420132673, mse=56516.85841571943
Iteration: 60000, B1=5.889820420132673, mse=56516.85841571943
Iteration: 80000, B1=5.889820420132673, mse=56516.85841571943
